/**
 * Clash of Clans API
 * Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LabelList } from './labelList';
import { League } from './league';
import { PlayerAchievementProgressList } from './playerAchievementProgressList';
import { PlayerClan } from './playerClan';
import { PlayerItemLevelList } from './playerItemLevelList';
import { PlayerLegendStatistics } from './playerLegendStatistics';

export interface Player { 
    clan?: PlayerClan;
    league?: League;
    role?: string;
    attackWins?: number;
    defenseWins?: number;
    townHallLevel?: number;
    townHallWeaponLevel?: number;
    versusBattleWins?: number;
    legendStatistics?: PlayerLegendStatistics;
    troops?: PlayerItemLevelList;
    heroes?: PlayerItemLevelList;
    spells?: PlayerItemLevelList;
    labels?: LabelList;
    tag?: string;
    name?: string;
    expLevel?: number;
    trophies?: number;
    bestTrophies?: number;
    donations?: number;
    donationsReceived?: number;
    builderHallLevel?: number;
    versusTrophies?: number;
    bestVersusTrophies?: number;
    warStars?: number;
    achievements?: PlayerAchievementProgressList;
    versusBattleWinCount?: number;
}